# Generated by Django 5.2.8 on 2025-11-16 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('target_type', models.CharField(choices=[('BLOG', 'Blog'), ('PRICING', 'Pricing Page'), ('NEWS', 'News/Announcements'), ('CAREERS', 'Careers Page'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('last_scraped_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.competitor')),
            ],
            options={
                'unique_together': {('competitor', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RELEASE', 'Product Release'), ('CAMPAIGN', 'Marketing Campaign'), ('PRICING', 'Pricing Change'), ('HIRING', 'Key Hiring'), ('NEWS', 'News/PR'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('source_url', models.URLField(max_length=1000)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.competitor')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='core.scrapetarget')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
